admin_user: jh
cockpit_user: cockpit
services:
  enabled:
    - adguard
    - beszel-pod
    - beszel-agent
    - beszel-ui
    - cloudflared
    - couchdb
    - glance
    - grafana
    - immobot
    - n8n
    - onedev
    - papra
    - registry
    - traefik
    - vaultwarden
    - wg-easy
  disabled:
    - homeassistant
    - homepage
    - matter
    - otbr