apiVersion: 1

datasources:
  - name: influxdb-1
    type: influxdb
    access: proxy
    url: http://localhost:8181
    jsonData:
      dbName: elektrotiegs-main
      version: SQL
      insecureGrpc: True
    secureJsonData:
      token: $INFLUXDB_ACCESS_TOKEN
