- name: configure podman containers and configuration data
  hosts: homelab
  remote_user: "{{ podman_user }}"
  tasks:
    # https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#podman-rootless-unit-search-path
    - name: Sync rootless quadlets
      ansible.posix.synchronize:
        src: ../quadlets/rootless/
        dest: ~/.config/containers/systemd/

    - name: Copy config
      ansible.posix.synchronize:
        src: ../config/
        dest: ~/containers/config/

    # - name: Restore backup data where necessary
    #   ansible.builtin.copy:
    #     src: ../storage/
    #     dest: /home/{{ podman_user }}/containers/storage/
    #     owner: "{{ podman_user }}"
    #     group: "{{ podman_user }}"
    #     mode: "0644"
    #     force: false # Don't overwrite existing app states

    - name: Force systemd to reload configs
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
