- name: Decrypt and sync secret files
  hosts: homelab
  gather_facts: true
  remote_user: "{{ podman_user }}"
  vars:
    target_secrets_path: ~/containers/secrets

  tasks:
    - name: Debug item basename
      ansible.builtin.debug:
        msg: "Basename of file is {{ item | basename }}"
      loop: "{{ lookup('fileglob', '../secrets/*.env', wantlist=True) }}"

    - name: Fetch age decryption key from vaultwarden
      local_action: ansible.builtin.shell BW_SESSION=$(bw unlock {{ bw_master_pw }} --raw) bw get item 5cbdfdb6-f629-454a-a37f-bf763a721586 | jq -r '.fields[] | select(.name == "private key") | .value'
      register: age_key
      changed_when: false
      no_log: true

    - name: Check decryption key
      ansible.builtin.debug:
        var: age_key
        verbosity: 2 # show only with -vv

    - name: Decrypt and copy secrets
      block:
        - name: Create temporary directory for copying secrets
          ansible.builtin.tempfile:
            state: directory
            suffix: _secrets
          register: tmp_secrets_dir

        - name: Decrypt and copy to tmp dir
          ansible.builtin.copy:
            content: "{{ lookup('file', item) | community.sops.decrypt(age_key=age_key.stdout, input_type='dotenv', output_type='dotenv') }}"
            dest: "{{ tmp_secrets_dir.path }}/{{ item | basename | regex_replace('\\.enc', '') }}"
            mode: 0o600
          loop: "{{ lookup('fileglob', '../secrets/*.env', wantlist=True) }}"

        - name: Clear all existing secrets from target directory
          ansible.builtin.file:
            path: "{{ target_secrets_path }}"
            state: absent

        - name: Move tmp secrets to final location
          ansible.builtin.command: mv "{{ tmp_secrets_dir.path }}" "{{ target_secrets_path }}"

      always:
        - name: Cleanup tmp secrets directory
          ansible.builtin.file:
            path: "{{ tmp_secrets_dir.path }}"
            state: absent
